### ISSUE TITLE
cordova 8.0.0 "error: package com.datecs.api does not exist"

### ISSUE THREAD

**Issue by eduardoaw** [giorgiofellipe/cordova-plugin-datecs-printer#110]
Provisional solution to solve error <b>error: package com.datecs.api does not exist</b>

<pre><code>mkdir -p platforms/android/cordova-plugin-datecs-printer

echo "repositories{ jcenter() flatDir{ dirs 'libs'} } dependencies { compile(name:'com.datecs.api', ext:'jar') } android { packagingOptions {exclude 'META-INF/NOTICE' exclude 'META-INF/LICENSE'}}" >> platforms/android/cordova-plugin-datecs-printer/app-datecsprinter.gradle

cp platforms/android/libs/com.datecs.api.jar platforms/android/app/libs/

sed -i 's#// PLUGIN GRADLE EXTENSIONS END#apply from: "../cordova-plugin-datecs-printer/app-datecsprinter.gradle"#g' platforms/android/cordova-plugin-datecs-printer/app-datecsprinter.gradle</pre></code>

Complete trace:

<pre><code>:app:compileReleaseJavaWithJavac/home/apps/platforms/android/app/src/main/java/com/giorgiofellipe/datecsprinter/DatecsSDKWrapper.java:41: error: package com.datecs.api does not exist
import com.datecs.api.BuildInfo;
                     ^
/home/apps/platforms/android/app/src/main/java/com/giorgiofellipe/datecsprinter/DatecsSDKWrapper.java:42: error: package com.datecs.api.printer does not exist
import com.datecs.api.printer.ProtocolAdapter;
                             ^
/home/apps/platforms/android/app/src/main/java/com/giorgiofellipe/datecsprinter/Printer.java:3: error: package com.datecs.api.biometric does not exist
import com.datecs.api.biometric.TouchChip;
                               ^
/home/apps/platforms/android/app/src/main/java/com/giorgiofellipe/datecsprinter/DatecsSDKWrapper.java:47: error: cannot find symbol
    private ProtocolAdapter mProtocolAdapter;
            ^
  symbol:   class ProtocolAdapter
  location: class DatecsSDKWrapper
/home/apps/platforms/android/app/src/main/java/com/giorgiofellipe/datecsprinter/DatecsSDKWrapper.java:61: error: package ProtocolAdapter does not exist
    private final ProtocolAdapter.PrinterListener mChannelListener = new ProtocolAdapter.PrinterListener() {
                                 ^
/home/apps/platforms/android/app/src/main/java/com/giorgiofellipe/datecsprinter/Printer.java:1357: error: cannot find symbol
    public TouchChip getTouchChip() {
           ^
  symbol:   class TouchChip
  location: class Printer
/home/apps/platforms/android/app/src/main/java/com/giorgiofellipe/datecsprinter/DatecsSDKWrapper.java:61: error: package ProtocolAdapter does not exist
    private final ProtocolAdapter.PrinterListener mChannelListener = new ProtocolAdapter.PrinterListener() {
                                                                                        ^
/home/apps/platforms/android/app/src/main/java/com/giorgiofellipe/datecsprinter/DatecsSDKWrapper.java:360: error: cannot find symbol
        mProtocolAdapter = new ProtocolAdapter(inputStream, outputStream);
                               ^
  symbol:   class ProtocolAdapter
  location: class DatecsSDKWrapper
/home/apps/platforms/android/app/src/main/java/com/giorgiofellipe/datecsprinter/DatecsSDKWrapper.java:364: error: package ProtocolAdapter does not exist
            final ProtocolAdapter.Channel channel = mProtocolAdapter.getChannel(ProtocolAdapter.CHANNEL_PRINTER);
                                 ^
/home/apps/platforms/android/app/src/main/java/com/giorgiofellipe/datecsprinter/DatecsSDKWrapper.java:364: error: cannot find symbol
            final ProtocolAdapter.Channel channel = mProtocolAdapter.getChannel(ProtocolAdapter.CHANNEL_PRINTER);
                                                                                ^
  symbol:   variable ProtocolAdapter
  location: class DatecsSDKWrapper
/home/apps/platforms/android/app/src/main/java/com/giorgiofellipe/datecsprinter/Printer.java:1358: error: cannot find symbol
        TouchChip instance = new TouchChip() {
        ^
  symbol:   class TouchChip
  location: class Printer
/home/apps/platforms/android/app/src/main/java/com/giorgiofellipe/datecsprinter/Printer.java:1358: error: cannot find symbol
        TouchChip instance = new TouchChip() {
                                 ^
  symbol:   class TouchChip
  location: class Printer
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
12 errors
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 22s</pre></code>

<pre><code>cordova 8.0.0
gradle 4.9
cordova-plugin-datecs-printer 0.8.2
android sdk 26.0.3
android sdk tools 4333796
node 8.9.0
</pre></code>

**Comment by giorgiofellipe** [comment]
Should be working on version 0.8.3.
